package.cpath = package.cpath .. ";./?.so"

local curses = require("curses")

--print(COLOR_MAGENTA, COLOR_RED, COLOR_BLACK, COLOR_YELLOW, COLOR_CYAN)

local screen = curses.initscr()
curses.noraw()
curses.cbreak()
curses.scrollok(screen, true)
curses.curs_set(2)
curses.move(2, 2)
curses.insch("A")
curses.addstr("hello this is a test string")
curses.mvaddstr(5, 40, "BONJOUR MADAME")
curses.box(screen, "|", "-")
curses.move(10, 1)
curses.hline("*", 20)
curses.move(10, 40)
curses.vline("$", 5)
curses.wstandout(screen)
curses.mvaddstr(15, 50, "standing out")
curses.wstandend(screen)
curses.mvaddstr(16, 50, "not standing out")
curses.mvaddstr(17, 45, "baudrate = " .. tostring(curses.baudrate()))
curses.refresh()
curses.getch()
curses.clear()
curses.addstr(string.format("has colors? => %q\n", curses.has_colors()))
curses.refresh()
curses.endwin()
